import type { Metadata } from "next";
import "./globals.css";
import { AntdRegistry } from "@ant-design/nextjs-registry"

export const metadata: Metadata = {
  title: "Mad Brindes",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body id="root-layout">
        <AntdRegistry>{children}</AntdRegistry>
      </body>
    </html>
  );
}
